version: '3.2'

services:
  proxy:
    ports:
      - "80:80"
      - "443:443"

  nginx:
    depends_on:
      - proxy
      - varnish

  ckan:
    depends_on:
      - datapusher
    links:
      - datapusher

    image: viderum/ckan-cloud-docker:ckan-latest-honduras-theme
    build:
      args:
        EXTRA_PACKAGES: supervisor cron
        EXTRA_FILESYSTEM: "./overrides/honduras/filesystem/"
        POST_INSTALL: |
          install_standard_ckan_extension_github -r datopian/ckanext-s3filestore -b fix-null-content-type &&\
          install_standard_ckan_extension_github -r ckan/ckanext-harvest -b 819706ae5dce5c62b2283fd8405fd8b6fa804355 &&\
          install_standard_ckan_extension_github -r okfn/ckanext-geoview -b v0.0.14 &&\
          install_standard_ckan_extension_github -r okfn/ckanext-pdfview -b lacounts-0.1 &&\
          install_standard_ckan_extension_github -r ckan/ckanext-googleanalytics &&\
          install_standard_ckan_extension_github -r ckan/ckanext-spatial &&\
          install_standard_ckan_extension_github -r ckan/ckanext-scheming &&\
          install_standard_ckan_extension_github -r ckan/ckanext-showcase  &&\
          install_standard_ckan_extension_github -r ckan/ckanext-pages -b bf25e93f98d1988db0614666afff11b14edd1b4b &&\
          install_standard_ckan_extension_github -r okfn/ckanext-sentry  &&\
          install_standard_ckan_extension_github -r ckan/ckanext-dcat  &&\
          install_standard_ckan_extension_github -r okfn/ckanext-envvars &&\
          install_standard_ckan_extension_github -r datopian/ckanext-honduras -b 0.0.20
        ROOT_INIT: |
          mkdir -p /var/log/supervisor
          chown ckan:ckan /var/log/supervisor
        POST_DOCKER_BUILD: |
          mkdir -p /var/log/ckan/std/
        CKAN_INIT: |
          ckan-paster --plugin=ckanext-harvest harvester initdb  -c "CKAN_CONFIG/production.ini"
          crontab /etc/crontab-harvester
          service supervisor start #rev1
    environment:
    - CKAN_CONFIG_TEMPLATE_PREFIX=honduras-theme-
  jobs:
    image: viderum/ckan-cloud-docker:ckan-latest-honduras-theme
    environment:
    - CKAN_CONFIG_TEMPLATE_PREFIX=honduras-theme-

  db:
    image: mdillon/postgis
    build:
      args:
        DB_INIT: |
          psql --dbname="ckan" -c "CREATE EXTENSION IF NOT EXISTS postgis;                  \
                                   CREATE EXTENSION IF NOT EXISTS postgis_topology;         \
                                   CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;            \
                                   CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder;"

  datapusher:
    container_name: datapusher
