name: Continuous Deployment
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
      - name: Deploy
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: |
          curl -L https://raw.githubusercontent.com/OriHoch/travis-ci-operator/master/travis_ci_operator.sh > $HOME/bin/travis_ci_operator.sh
          bash $HOME/bin/travis_ci_operator.sh init
          bash .travis.sh install
          bash .travis.sh script
          bash .travis.sh deploy
